/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/barrels.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/barrels.tsx -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GLTFAction } from "@/components/types";
import { CuboidCollider, RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    barrels_2: THREE.Mesh;
    barrels_3: THREE.Mesh;
  };
  materials: {
    barrel: THREE.MeshBasicMaterial;
    planks: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[]; 
};

interface iBarrels {
  groupProps: React.ComponentProps<"group">
  rigidBodyType: "fixed" | "dynamic" | "kinematic"
}

export function Barrels(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "/models/kenney/retroMedieval/barrels.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed">
        <CuboidCollider args={[.5, .5, .35]} position={[0, 0, 0]} restitution={0}/>
        <mesh geometry={nodes.barrels_2.geometry} material={materials.barrel} />
        <mesh geometry={nodes.barrels_3.geometry} material={materials.planks} />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/barrels.glb");
