/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/battlement-half.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/battlement-half.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['battlement-half_2']: THREE.Mesh
    ['battlement-half_3']: THREE.Mesh
  }
  materials: {
    stones: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function BattlementHalf(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/battlement-half.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['battlement-half_2'].geometry} material={materials.stones} />
      <mesh geometry={nodes['battlement-half_3'].geometry} material={materials.bricks} />
    </group>
  )
}

useGLTF.preload('/battlement-half.glb')
