/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/battlement-corner-outer.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/battlement-corner-outer.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['battlement-corner-outer_2']: THREE.Mesh
    ['battlement-corner-outer_3']: THREE.Mesh
  }
  materials: {
    bricks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function BattlementCornerOuter(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/battlement-corner-outer.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['battlement-corner-outer_2'].geometry} material={materials.bricks} />
      <mesh geometry={nodes['battlement-corner-outer_3'].geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/battlement-corner-outer.glb')
