/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/bricks.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/bricks.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    bricks_1: THREE.Mesh
  }
  materials: {
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Bricks(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/bricks.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bricks_1.geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/bricks.glb')
