/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/detail-crate-ropes.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/detail-crate-ropes.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['detail-crate-ropes_2']: THREE.Mesh
    ['detail-crate-ropes_3']: THREE.Mesh
  }
  materials: {
    barrel: THREE.MeshBasicMaterial
    details: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function DetailCrateRopes(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/detail-crate-ropes.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['detail-crate-ropes_2'].geometry} material={materials.barrel} />
      <mesh geometry={nodes['detail-crate-ropes_3'].geometry} material={materials.details} />
    </group>
  )
}

useGLTF.preload('/detail-crate-ropes.glb')
