/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/fence-wood.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/fence-wood.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['fence-wood_1']: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function FenceWood(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/fence-wood.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['fence-wood_1'].geometry} material={materials.planks} />
    </group>
  )
}

useGLTF.preload('/fence-wood.glb')
