/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/floor-steps.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/floor-steps.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['floor-steps_2']: THREE.Mesh
    ['floor-steps_3']: THREE.Mesh
  }
  materials: {
    bricks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UfloorUsteps(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/floor-steps.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['floor-steps_2'].geometry} material={materials.bricks} />
      <mesh geometry={nodes['floor-steps_3'].geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/floor-steps.glb')
