/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/floor.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/floor.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    floor_2: THREE.Mesh
    floor_3: THREE.Mesh
  }
  materials: {
    bricks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Ufloor(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/floor.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor_2.geometry} material={materials.bricks} />
      <mesh geometry={nodes.floor_3.geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('floor.glb')
