/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/ladder.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/ladder.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ladder_1: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Uladder(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/ladder.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ladder_1.geometry} material={materials.planks} />
    </group>
  )
}

useGLTF.preload('/ladder.glb')
