/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/overhang-round-railing.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/overhang-round-railing.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['overhang-round-railing_1']: THREE.Mesh
    Group: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UoverhangUroundUrailing(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/overhang-round-railing.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['overhang-round-railing_1'].geometry} material={materials.planks}>
        <mesh geometry={nodes.Group.geometry} material={materials.planks} position={[0, 0.3, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/overhang-round-railing.glb')
