/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/pulley-crate.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/pulley-crate.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['pulley-crate_2']: THREE.Mesh
    ['pulley-crate_3']: THREE.Mesh
    ['pulley-crate_4']: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
    details: THREE.MeshBasicMaterial
    barrel: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UpulleyUcrate(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/pulley-crate.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['pulley-crate_2'].geometry} material={materials.planks} />
      <mesh geometry={nodes['pulley-crate_3'].geometry} material={materials.details} />
      <mesh geometry={nodes['pulley-crate_4'].geometry} material={materials.barrel} />
    </group>
  )
}

useGLTF.preload('/pulley-crate.glb')
