/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/pulley.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/pulley.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    pulley_2: THREE.Mesh
    pulley_3: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
    details: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Upulley(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/pulley.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pulley_2.geometry} material={materials.planks} />
      <mesh geometry={nodes.pulley_3.geometry} material={materials.details} />
    </group>
  )
}

useGLTF.preload('/pulley.glb')
