/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/roof-edge.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/roof-edge.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['roof-edge_2']: THREE.Mesh
    ['roof-edge_3']: THREE.Mesh
    ['roof-edge_4']: THREE.Mesh
    ['roof-edge_5']: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
    roof: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UroofUedge(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/roof-edge.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['roof-edge_2'].geometry} material={materials.planks} />
      <mesh geometry={nodes['roof-edge_3'].geometry} material={materials.roof} />
      <mesh geometry={nodes['roof-edge_4'].geometry} material={materials.bricks} />
      <mesh geometry={nodes['roof-edge_5'].geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/roof-edge.glb')
