/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/roof.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/roof.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    roof_2: THREE.Mesh
    roof_3: THREE.Mesh
    roof_4: THREE.Mesh
    roof_5: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
    roof: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Roof(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/roof.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.roof_2.geometry} material={materials.planks} />
      <mesh geometry={nodes.roof_3.geometry} material={materials.roof} />
      <mesh geometry={nodes.roof_4.geometry} material={materials.bricks} />
      <mesh geometry={nodes.roof_5.geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/roof.glb')
