/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/roof-side-corner.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/roof-side-corner.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['roof-side-corner_2']: THREE.Mesh
    ['roof-side-corner_3']: THREE.Mesh
    ['roof-side-corner_4']: THREE.Mesh
  }
  materials: {
    stones: THREE.MeshBasicMaterial
    roof: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UroofUsideUcorner(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/roof-side-corner.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['roof-side-corner_2'].geometry} material={materials.stones} />
      <mesh geometry={nodes['roof-side-corner_3'].geometry} material={materials.roof} />
      <mesh geometry={nodes['roof-side-corner_4'].geometry} material={materials.bricks} />
    </group>
  )
}

useGLTF.preload('/roof-side-corner.glb')
