/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/stairs-stone.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/stairs-stone.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['stairs-stone_2']: THREE.Mesh
    ['stairs-stone_3']: THREE.Mesh
    ['stairs-stone_4']: THREE.Mesh
  }
  materials: {
    stones: THREE.MeshBasicMaterial
    planks: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UstairsUstone(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/stairs-stone.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['stairs-stone_2'].geometry} material={materials.stones} />
      <mesh geometry={nodes['stairs-stone_3'].geometry} material={materials.planks} />
      <mesh geometry={nodes['stairs-stone_4'].geometry} material={materials.bricks} />
    </group>
  )
}

useGLTF.preload('/stairs-stone.glb')
