/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/structure-poles.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/structure-poles.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['structure-poles_1']: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UstructureUpoles(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/structure-poles.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['structure-poles_1'].geometry} material={materials.planks} />
    </group>
  )
}

useGLTF.preload('/structure-poles.glb')
