/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/tree-shrub.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/tree-shrub.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['tree-shrub_1']: THREE.Mesh
  }
  materials: {
    tree: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function MedievalTreeShrub(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/tree-shrub.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-shrub_1'].geometry} material={materials.tree} />
    </group>
  )
}

useGLTF.preload('/tree-shrub.glb')
