/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/wall-pane.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/wall-pane.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-pane_1']: THREE.Mesh
  }
  materials: {
    stones: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function WallBDetailPaintedUpane(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/wall-pane.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-pane_1'].geometry} material={materials.stones} />
    </group>
  )
}

useGLTF.preload('/wall-pane.glb')
