/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/wall-pane-painted-wood-door.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/wall-pane-painted-wood-door.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-pane-painted-wood-door_2']: THREE.Mesh
    ['wall-pane-painted-wood-door_3']: THREE.Mesh
    ['wall-pane-painted-wood-door_4']: THREE.Mesh
  }
  materials: {
    stonesPainted: THREE.MeshBasicMaterial
    planks: THREE.MeshBasicMaterial
    details: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function WallBDetailPaintedUpaneUpaintedUwoodUdoor(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/wall-pane-painted-wood-door.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-pane-painted-wood-door_2'].geometry} material={materials.stonesPainted} />
      <mesh geometry={nodes['wall-pane-painted-wood-door_3'].geometry} material={materials.planks} />
      <mesh geometry={nodes['wall-pane-painted-wood-door_4'].geometry} material={materials.details} />
    </group>
  )
}

useGLTF.preload('/wall-pane-painted-wood-door.glb')
