/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/wall-paint-detail.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/wall-paint-detail.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-paint-detail_2']: THREE.Mesh
    ['wall-paint-detail_3']: THREE.Mesh
  }
  materials: {
    stonesPainted: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function WallBDetailPaintedUpaintUdetail(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/wall-paint-detail.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-paint-detail_2'].geometry} material={materials.stonesPainted} />
      <mesh geometry={nodes['wall-paint-detail_3'].geometry} material={materials.bricks} />
    </group>
  )
}

useGLTF.preload('/wall-paint-detail.glb')
