/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/wall-fortified-half.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/wall-fortified-half.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-fortified-half_2']: THREE.Mesh
    ['wall-fortified-half_3']: THREE.Mesh
    ['wall-fortified-half_4']: THREE.Mesh
  }
  materials: {
    planks: THREE.MeshBasicMaterial
    stones: THREE.MeshBasicMaterial
    bricks: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function WallBDetailPaintedUfortifiedUhalf(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroMedieval/wall-fortified-half.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-fortified-half_2'].geometry} material={materials.planks} />
      <mesh geometry={nodes['wall-fortified-half_3'].geometry} material={materials.stones} />
      <mesh geometry={nodes['wall-fortified-half_4'].geometry} material={materials.bricks} />
    </group>
  )
}

useGLTF.preload('/wall-fortified-half.glb')
