/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroMedieval/wall-fortified-gate.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroMedieval/wall-fortified-gate.tsx -t 
*/

import * as THREE from "three";
import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GLTFAction } from "@/components/game/types";
import {
  CuboidCollider,
  RigidBody,
  TrimeshCollider,
} from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    ["wall-fortified-gate_2"]: THREE.Mesh;
    ["wall-fortified-gate_3"]: THREE.Mesh;
    ["wall-fortified-gate_4"]: THREE.Mesh;
  };
  materials: {
    planks: THREE.MeshBasicMaterial;
    stones: THREE.MeshBasicMaterial;
    bricks: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};

export function WallBDetailPaintedFortifiedGate(
  props: React.ComponentProps<"group">,
) {
  const { nodes, materials } = useGLTF(
    "/models/kenney/retroMedieval/wall-fortified-gate.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders={false}>
        <mesh
          geometry={nodes["wall-fortified-gate_2"].geometry}
          material={materials.planks}
        />
        <CuboidCollider args={[.15, 1, .8]} position={[-.35, 0, 0]} />
        <CuboidCollider args={[.15, 1, .8]} position={[.35, 0, 0]} />
        <mesh
          geometry={nodes["wall-fortified-gate_3"].geometry}
          material={materials.stones}
        />
        <mesh
          geometry={nodes["wall-fortified-gate_4"].geometry}
          material={materials.bricks}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/wall-fortified-gate.glb");
