/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/balcony-type-a.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/balcony-type-a.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['balcony-type-a_1']: THREE.Mesh
  }
  materials: {
    bars: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UbalconyUtypeUa(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/balcony-type-a.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['balcony-type-a_1'].geometry} material={materials.bars} />
    </group>
  )
}

useGLTF.preload('/balcony-type-a.glb')
