/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/cliff-side.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/cliff-side.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['cliff-side_2']: THREE.Mesh
    ['cliff-side_3']: THREE.Mesh
  }
  materials: {
    grass: THREE.MeshBasicMaterial
    rock: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UcliffUside(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/cliff-side.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['cliff-side_2'].geometry} material={materials.grass} />
      <mesh geometry={nodes['cliff-side_3'].geometry} material={materials.rock} />
    </group>
  )
}

useGLTF.preload('/cliff-side.glb')
