/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/cliff-corner.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/cliff-corner.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['cliff-corner_2']: THREE.Mesh
    ['cliff-corner_3']: THREE.Mesh
  }
  materials: {
    rock: THREE.MeshBasicMaterial
    grass: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UcliffUcorner(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/cliff-corner.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['cliff-corner_2'].geometry} material={materials.rock} />
      <mesh geometry={nodes['cliff-corner_3'].geometry} material={materials.grass} />
    </group>
  )
}

useGLTF.preload('/cliff-corner.glb')
