/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/detail-barrier-strong-type-b.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/detail-barrier-strong-type-b.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['detail-barrier-strong-type-b_2']: THREE.Mesh
    ['detail-barrier-strong-type-b_3']: THREE.Mesh
  }
  materials: {
    concrete: THREE.MeshBasicMaterial
    signs: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UdetailUbarrierUstrongUtypeUb(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/detail-barrier-strong-type-b.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['detail-barrier-strong-type-b_2'].geometry} material={materials.concrete} />
      <mesh geometry={nodes['detail-barrier-strong-type-b_3'].geometry} material={materials.signs} />
    </group>
  )
}

useGLTF.preload('/detail-barrier-strong-type-b.glb')
