/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/detail-cables-type-b.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/detail-cables-type-b.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['detail-cables-type-b_1']: THREE.Mesh
  }
  materials: {
    signs: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UdetailUcablesUtypeUb(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/detail-cables-type-b.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['detail-cables-type-b_1'].geometry} material={materials.signs} />
    </group>
  )
}

useGLTF.preload('/detail-cables-type-b.glb')
