/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/detail-dumpster-closed.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/detail-dumpster-closed.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['detail-dumpster-closed_2']: THREE.Mesh
    ['detail-dumpster-closed_3']: THREE.Mesh
    ['detail-dumpster-closed_4']: THREE.Mesh
  }
  materials: {
    wall_metal: THREE.MeshBasicMaterial
    wall: THREE.MeshBasicMaterial
    roof: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UdetailUdumpsterUclosed(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/detail-dumpster-closed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['detail-dumpster-closed_2'].geometry} material={materials.wall_metal} />
      <mesh geometry={nodes['detail-dumpster-closed_3'].geometry} material={materials.wall} />
      <mesh geometry={nodes['detail-dumpster-closed_4'].geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/detail-dumpster-closed.glb')
