/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/detail-awning-small.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/detail-awning-small.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['detail-awning-small_1']: THREE.Mesh
  }
  materials: {
    roof: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UdetailUawningUsmall(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/detail-awning-small.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['detail-awning-small_1'].geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/detail-awning-small.glb')
