/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/grass.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/grass.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    grass_1: THREE.Mesh
  }
  materials: {
    grass: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Ugrass(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/grass.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.grass_1.geometry} material={materials.grass} />
    </group>
  )
}

useGLTF.preload('/grass.glb')
