/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/road-asphalt-side.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/road-asphalt-side.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['road-asphalt-side_2']: THREE.Mesh
    ['road-asphalt-side_3']: THREE.Mesh
  }
  materials: {
    asphalt: THREE.MeshBasicMaterial
    concreteSmooth: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UroadUasphaltUside(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/road-asphalt-side.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['road-asphalt-side_2'].geometry} material={materials.asphalt} />
      <mesh geometry={nodes['road-asphalt-side_3'].geometry} material={materials.concreteSmooth} />
    </group>
  )
}

useGLTF.preload('/road-asphalt-side.glb')
