/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/road-asphalt-center.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/road-asphalt-center.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['road-asphalt-center_1']: THREE.Mesh
  }
  materials: {
    asphalt: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UroadUasphaltUcenter(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/road-asphalt-center.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['road-asphalt-center_1'].geometry} material={materials.asphalt} />
    </group>
  )
}

useGLTF.preload('/road-asphalt-center.glb')
