/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/scaffolding-floor.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/scaffolding-floor.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['scaffolding-floor_2']: THREE.Mesh
    ['scaffolding-floor_3']: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshBasicMaterial
    bars: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UscaffoldingUfloor(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/scaffolding-floor.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['scaffolding-floor_2'].geometry} material={materials.metal} />
      <mesh geometry={nodes['scaffolding-floor_3'].geometry} material={materials.bars} />
    </group>
  )
}

useGLTF.preload('/scaffolding-floor.glb')
