/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/tree-park-pine-large.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/tree-park-pine-large.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['tree-park-pine-large_2']: THREE.Mesh
    ['tree-park-pine-large_3']: THREE.Mesh
    ['tree-park-pine-large_4']: THREE.Mesh
  }
  materials: {
    treeB: THREE.MeshBasicMaterial
    concreteSmooth: THREE.MeshBasicMaterial
    dirt: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UtreeUparkUpineUlarge(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/tree-park-pine-large.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-park-pine-large_2'].geometry} material={materials.treeB} />
      <mesh geometry={nodes['tree-park-pine-large_3'].geometry} material={materials.concreteSmooth} />
      <mesh geometry={nodes['tree-park-pine-large_4'].geometry} material={materials.dirt} />
    </group>
  )
}

useGLTF.preload('/tree-park-pine-large.glb')
