/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/tree-large.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/tree-large.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['tree-large_1']: THREE.Mesh
  }
  materials: {
    treeA: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UtreeUlarge(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/tree-large.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-large_1'].geometry} material={materials.treeA} />
    </group>
  )
}

useGLTF.preload('/tree-large.glb')
