/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/truck-flat.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/truck-flat.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['truck-flat_2']: THREE.Mesh
    ['truck-flat_3']: THREE.Mesh
  }
  materials: {
    truck: THREE.MeshBasicMaterial
    metal: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UtruckUflat(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/truck-flat.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['truck-flat_2'].geometry} material={materials.truck} />
      <mesh geometry={nodes['truck-flat_3'].geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/truck-flat.glb')
