/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/truck-grey.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/truck-grey.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['truck-grey_1']: THREE.Mesh
  }
  materials: {
    truck: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UtruckUgrey(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/truck-grey.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['truck-grey_1'].geometry} material={materials.truck} />
    </group>
  )
}

useGLTF.preload('/truck-grey.glb')
