/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/truck-grey-cargo.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/truck-grey-cargo.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['truck-grey-cargo_1']: THREE.Mesh
  }
  materials: {
    truck: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UtruckUgreyUcargo(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/truck-grey-cargo.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['truck-grey-cargo_1'].geometry} material={materials.truck} />
    </group>
  )
}

useGLTF.preload('/truck-grey-cargo.glb')
