/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/wall-c-flat.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/wall-c-flat.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-c-flat_1']: THREE.Mesh
  }
  materials: {
    bars: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function WallBDetailPaintedUcUflat(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/wall-c-flat.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-c-flat_1'].geometry} material={materials.bars} />
    </group>
  )
}

useGLTF.preload('/wall-c-flat.glb')
