/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/wall-b-detail-painted.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/wall-b-detail-painted.tsx -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GLTFAction } from "@/components/game/types";

type GLTFResult = GLTF & {
  nodes: {
    ["wall-b-detail-painted_2"]: THREE.Mesh;
    ["wall-b-detail-painted_3"]: THREE.Mesh;
    ["wall-b-detail-painted_4"]: THREE.Mesh;
    ["wall-b-detail-painted_5"]: THREE.Mesh;
  };
  materials: {
    _defaultMat: THREE.MeshBasicMaterial;
    concrete: THREE.MeshBasicMaterial;
    wall_metal: THREE.MeshBasicMaterial;
    wall: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};

export function WallBDetailPainted(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "/models/kenney/retroUrban/wall-b-detail-painted.glb",
  ) as unknown as GLTFResult;
  const defaultMat = new THREE.MeshStandardMaterial({
    map: materials._defaultMat.map, // <--- Extract the texture image from the original
    color: materials._defaultMat.color,
    roughness: 1,
    metalness: 0,
  });
  const concrete = new THREE.MeshStandardMaterial({
    map: materials.concrete.map, // <--- Extract the texture image from the original
    color: materials.concrete.color,
    roughness: 1,
    metalness: 0,
  });

  const wall_metal = new THREE.MeshStandardMaterial({
    map: materials.wall_metal.map, // <--- Extract the texture image from the original
    color: materials.wall_metal.color,
    roughness: 1,
    metalness: 0,
  });

  const wall = new THREE.MeshStandardMaterial({
    map: materials.wall.map, // <--- Extract the texture image from the original
    color: materials.wall.color,
    roughness: 1,
    metalness: 0,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["wall-b-detail-painted_2"].geometry}
        material={defaultMat}
      />
      <mesh
        geometry={nodes["wall-b-detail-painted_3"].geometry}
        material={concrete}
      />
      <mesh
        geometry={nodes["wall-b-detail-painted_4"].geometry}
        material={wall_metal}
      />
      <mesh
        geometry={nodes["wall-b-detail-painted_5"].geometry}
        material={wall}
      />
    </group>
  );
}

useGLTF.preload("/models/kenney/retroUrban/wall-b-detail-painted.glb");
