/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/wall-a-flat-window.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/wall-a-flat-window.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-a-flat-window_2']: THREE.Mesh
    ['wall-a-flat-window_3']: THREE.Mesh
    ['wall-a-flat-window_4']: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshBasicMaterial
    windows: THREE.MeshBasicMaterial
    wall_lines: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UwallUaUflatUwindow(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/wall-a-flat-window.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-a-flat-window_2'].geometry} material={materials.metal} />
      <mesh geometry={nodes['wall-a-flat-window_3'].geometry} material={materials.windows} />
      <mesh geometry={nodes['wall-a-flat-window_4'].geometry} material={materials.wall_lines} />
    </group>
  )
}

useGLTF.preload('/wall-a-flat-window.glb')
