/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/wall-b-roof.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/wall-b-roof.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['wall-b-roof_2']: THREE.Mesh
    ['wall-b-roof_3']: THREE.Mesh
    ['wall-b-roof_4']: THREE.Mesh
  }
  materials: {
    concrete: THREE.MeshBasicMaterial
    roof_plates: THREE.MeshBasicMaterial
    wall_metal: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UwallUbUroof(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/wall-b-roof.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wall-b-roof_2'].geometry} material={materials.concrete} />
      <mesh geometry={nodes['wall-b-roof_3'].geometry} material={materials.roof_plates} />
      <mesh geometry={nodes['wall-b-roof_4'].geometry} material={materials.wall_metal} />
    </group>
  )
}

useGLTF.preload('/wall-b-roof.glb')
