/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/retroUrban/window-wide-type-b.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/retroUrban/window-wide-type-b.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['window-wide-type-b_2']: THREE.Mesh
    ['window-wide-type-b_3']: THREE.Mesh
  }
  materials: {
    windows: THREE.MeshBasicMaterial
    metal: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function UwindowUwideUtypeUb(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/retroUrban/window-wide-type-b.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['window-wide-type-b_2'].geometry} material={materials.windows} />
      <mesh geometry={nodes['window-wide-type-b_3'].geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/window-wide-type-b.glb')
