/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/fantasyTown/cart-high.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/fantasyTown/cart-high.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/types'

type GLTFResult = GLTF & {
  nodes: {
    ['cart-high_1']: THREE.Mesh
    Group: THREE.Mesh
    Group_1: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function UcartUhigh(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/fantasyTown/cart-high.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['cart-high_1'].geometry} material={materials.colormap}>
        <mesh geometry={nodes.Group.geometry} material={materials.colormap} position={[-0.325, 0, -0.039]} />
        <mesh geometry={nodes.Group_1.geometry} material={materials.colormap} position={[0.447, 0, -0.039]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cart-high.glb')
