/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/fantasyTown/fence-gate.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/fantasyTown/fence-gate.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['fence-gate_1']: THREE.Mesh
    gate: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function UfenceUgate(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/fantasyTown/fence-gate.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['fence-gate_1'].geometry} material={materials.colormap}>
        <mesh geometry={nodes.gate.geometry} material={materials.colormap} position={[0.463, 0.185, -0.2]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/fence-gate.glb')
