/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/fantasyTown/fountain-curved.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/fantasyTown/fountain-curved.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['fountain-curved_1']: THREE.Mesh
    ['(%ignore)']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function UfountainUcurved(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/fantasyTown/fountain-curved.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['fountain-curved_1'].geometry} material={materials.colormap}>
        <mesh geometry={nodes['(%ignore)'].geometry} material={materials.Water} position={[0.15, 0.14, 0.15]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/fountain-curved.glb')
