/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/fantasyTown/road-bend.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/fantasyTown/road-bend.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['road-bend_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function UroadUbend(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/fantasyTown/road-bend.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['road-bend_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/road-bend.glb')
