/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kenney/fantasyTown/roof-flat.glb -o /Users/Lee/Desktop/code/labrynth/src/components/game/models/kenney/fantasyTown/roof-flat.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'; 
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    ['roof-flat_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function UroofUflat(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/kenney/fantasyTown/roof-flat.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['roof-flat_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/roof-flat.glb')
