/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Barrel.glb -o Barrel.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder000: THREE.Mesh
    Cylinder000_1: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function BarrelQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/dungeon/Barrel.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder000.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Cylinder000_1.geometry} material={materials.Steel} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/dungeon/Barrel.glb')
