/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bars.glb -o Bars.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Bars: THREE.Mesh
  }
  materials: {
    Steel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function BarsQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/dungeon/Bars.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bars.geometry} material={materials.Steel} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/dungeon/Bars.glb')
