/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Book3.glb -o Book3.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube023: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
  }
  materials: {
    Cover: THREE.MeshStandardMaterial
    Paper: THREE.MeshStandardMaterial
    Ink: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Book3Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Book3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.115, 0]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.Paper} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.Ink} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/quaternius/Book3.glb')
