/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Book_Open.glb -o Book_Open.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube021: THREE.Mesh
    Cube021_1: THREE.Mesh
    Cube021_2: THREE.Mesh
  }
  materials: {
    Cover: THREE.MeshStandardMaterial
    Paper: THREE.MeshStandardMaterial
    Ink: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function BookOpenQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Book_Open.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube021.geometry} material={materials.Cover} />
      <mesh geometry={nodes.Cube021_1.geometry} material={materials.Paper} />
      <mesh geometry={nodes.Cube021_2.geometry} material={materials.Ink} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Book_Open.glb')
