/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Candelabrum.glb -o Candelabrum.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
  }
  materials: {
    Gold: THREE.MeshStandardMaterial
    Candle: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CandelabrumQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Candelabrum.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Candle} />
      <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Candelabrum.glb')
