/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Candle.glb -o Candle.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
  }
  materials: {
    ['Gold.001']: THREE.MeshStandardMaterial
    ['Candle.001']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CandleQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Candle.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Gold.001']} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Candle.001']} />
      <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Candle.glb')
