/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Carpet.glb -o Carpet.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
  }
  materials: {
    Red: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CarpetQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Carpet.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube014.geometry} material={materials.Red} />
      <mesh geometry={nodes.Cube014_1.geometry} material={materials.Gold} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Carpet.glb')
