/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chest.glb -o Chest.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder018_1: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
    DarkSteel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function ChestQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Chest.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.048, 0.622, 1.437]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials.Steel} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.DarkSteel} />
      </group>
      <group position={[-0.25, 0.603, 1.438]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials.Steel} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/quaternius/Chest.glb')
