/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Chest_gold.glb -o Chest_gold.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube024_2: THREE.Mesh
    Cube024_3: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder018_1: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
    DarkSteel: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function ChestGoldQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Chest_gold.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.389, 0.442, 0.015]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials.Steel} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.DarkSteel} />
        <mesh geometry={nodes.Cube024_3.geometry} material={materials.Gold} />
      </group>
      <group position={[0.091, 0.423, 0.016]} rotation={[0, 0, 0.751]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials.Steel} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/quaternius/Chest_gold.glb')
