/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Entrance2.glb -o Entrance2.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Entrance2: THREE.Mesh
  }
  materials: {
    Rock: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Entrance2Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Entrance2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Entrance2.geometry} material={materials.Rock} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Entrance2.glb')
