/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ModularFloor.glb -o ModularFloor.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube000: THREE.Mesh
    Cube000_1: THREE.Mesh
  }
  materials: {
    RockLight: THREE.MeshStandardMaterial
    Rock: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function FloorQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/ModularFloor.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube000.geometry} material={materials.RockLight} />
      <mesh geometry={nodes.Cube000_1.geometry} material={materials.Rock} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/ModularFloor.glb')
