/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion6.glb -o Potion6.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder017: THREE.Mesh
    Cylinder017_1: THREE.Mesh
  }
  materials: {
    Cork: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Potion6Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion6.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.Cork} />
      <mesh geometry={nodes.Cylinder017_1.geometry} material={materials.Yellow} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion6.glb')
