/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion2.glb -o Potion2.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder000: THREE.Mesh
    Cylinder000_1: THREE.Mesh
    Cylinder000_2: THREE.Mesh
  }
  materials: {
    Cork: THREE.MeshStandardMaterial
    Liquid: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Potion2Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder000.geometry} material={materials.Cork} />
      <mesh geometry={nodes.Cylinder000_1.geometry} material={materials.Liquid} />
      <mesh geometry={nodes.Cylinder000_2.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion2.glb')
