/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion.glb -o Potion.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder012: THREE.Mesh
    Cylinder012_1: THREE.Mesh
    Cylinder012_2: THREE.Mesh
  }
  materials: {
    Cork: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function PotionQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.Cork} />
      <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Cylinder012_2.geometry} material={materials.Gold} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion.glb')
