/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion3.glb -o Potion3.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder014: THREE.Mesh
    Cylinder014_1: THREE.Mesh
  }
  materials: {
    Grey: THREE.MeshStandardMaterial
    Ice: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Potion3Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.Grey} />
      <mesh geometry={nodes.Cylinder014_1.geometry} material={materials.Ice} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion3.glb')
