/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion4.glb -o Potion4.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder015: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
  }
  materials: {
    Cork: THREE.MeshStandardMaterial
    Liquid: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Potion4Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.Cork} />
      <mesh geometry={nodes.Cylinder015_1.geometry} material={materials.Liquid} />
      <mesh geometry={nodes.Cylinder015_2.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion4.glb')
