/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Potion5.glb -o Potion5.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
  }
  materials: {
    Liquid: THREE.MeshStandardMaterial
    Cork: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Potion5Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Potion5.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Liquid} />
      <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.Cork} />
      <mesh geometry={nodes.Cylinder016_2.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Potion5.glb')
