/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rock5.glb -o Rock5.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Rock5: THREE.Mesh
  }
  materials: {
    ['Rock.004']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Rock5Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Rock5.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock5.geometry} material={materials['Rock.004']} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Rock5.glb')
