/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rock4.glb -o Rock4.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Rock4: THREE.Mesh
  }
  materials: {
    ['Rock.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Rock4Q(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Rock4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock4.geometry} material={materials['Rock.003']} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Rock4.glb')
