/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Torch.glb -o Torch.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube000: THREE.Mesh
    Cube000_1: THREE.Mesh
    Cube000_2: THREE.Mesh
  }
  materials: {
    DarkSteel: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Fire: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function TorchQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Torch.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube000.geometry} material={materials.DarkSteel} />
      <mesh geometry={nodes.Cube000_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Cube000_2.geometry} material={materials.Fire} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Torch.glb')
