/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WallRocks.glb -o WallRocks.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    WallRocks: THREE.Mesh
  }
  materials: {
    RockLight: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function TileRocksQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/WallRocks.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WallRocks.geometry} material={materials.RockLight} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/WallRocks.glb')
