/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Window.glb -o Window.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from '@/components/game/types'

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
  }
  materials: {
    Rock: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    DarkSteel: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function WindowQ(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/quaternius/Window.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Rock} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube002_2.geometry} material={materials.DarkSteel} />
    </group>
  )
}

useGLTF.preload('/models/quaternius/Window.glb')
