/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mixamo/mainCharacter.glb -o src/components/game/models/mixamo/mainCharacter.tsx -t 
*/

import * as THREE from "three";
import React, { JSX, useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "Armature|mixamo.com|Layer0_Armature"
  | "Armature|mixamo.com|Layer0_Armature.001"
  | "Idle";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Guard02: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    Guard_02: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function MainCharacter(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/models/mixamo/mainCharacter.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Idle"]?.reset().fadeIn(0.2).play();
    return () => {
      actions["Idle"]?.fadeOut(0.2);
    };
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Guard02"
            geometry={nodes.Guard02.geometry}
            material={materials.Guard_02}
            skeleton={nodes.Guard02.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mixamo/mainCharacter.glb");
