/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mainCharacter.glb -o ../../../src/components/game/models/mixamo/mainCharacter.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|mixamo.com|Layer0'

type GLTFAction = THREE.AnimationClip & {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Guard03_Mesh: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Guard_03: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function MainCharacter(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/mixamo/mainCharacter.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Guard03_Mesh" geometry={nodes.Guard03_Mesh.geometry} material={materials.Guard_03} skeleton={nodes.Guard03_Mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mixamo/mainCharacter.glb')
