/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shopkeeper.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ShopkeeperModel(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/mixamo/shopkeeper.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="MAW" geometry={nodes.MAW.geometry} material={materials.MAW_MAT} skeleton={nodes.MAW.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mixamo/shopkeeper.glb')
