/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Skeleton.glb -o Skeleton.tsx --typesndone 
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "Armature|mixamo.com|Layer0";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Left_Thumb: THREE.Mesh;
    Left_Index: THREE.Mesh;
    Left_Middle: THREE.Mesh;
    Left_Pinky: THREE.Mesh;
    Left_Hand: THREE.Mesh;
    Left_Forearm: THREE.Mesh;
    Left_Arm: THREE.Mesh;
    Left_Shoulder: THREE.Mesh;
    Right_Index_Finger: THREE.Mesh;
    Right_Middle_Finger: THREE.Mesh;
    Right_Pinky: THREE.Mesh;
    Right_Thumb: THREE.Mesh;
    Wrist: THREE.Mesh;
    Right_Arm: THREE.Mesh;
    Right_Forearm: THREE.Mesh;
    Right_Shoulder: THREE.Mesh;
    Skull: THREE.Mesh;
    Ribs002: THREE.Mesh;
    Left_Toe_End: THREE.Mesh;
    Left_Toe_Base: THREE.Mesh;
    Left_Foot: THREE.Mesh;
    Left_Leg: THREE.Mesh;
    Left_Upper_Leg: THREE.Mesh;
    Right_Toe_End: THREE.Mesh;
    Right_Toe_Base: THREE.Mesh;
    Right_Foot: THREE.Mesh;
    Right_Leg: THREE.Mesh;
    Right_Upper_Leg: THREE.Mesh;
    Hip: THREE.Mesh;
    MAW: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
    neutral_bone: THREE.Bone;
  };
  materials: {
    MAW_MAT: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Skeleton(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group | null>(null);
  const { scene, animations } = useGLTF("/models/ldyer/Skeleton.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  const boneMaterial = <meshStandardMaterial color="#FFFFFF" roughness={0.8} />;

  return (
    <group ref={group} {...props} dispose={null}>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.neutral_bone} />

          {/* skull */}
          <mesh geometry={nodes.Skull.geometry}>{boneMaterial}</mesh>

          {/* torso */}
          <mesh geometry={nodes.Ribs002.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Hip.geometry}>{boneMaterial}</mesh>

          {/* left arm */}
          <mesh geometry={nodes.Left_Shoulder.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Arm.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Forearm.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Hand.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Thumb.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Index.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Middle.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Pinky.geometry}>{boneMaterial}</mesh>

          {/* right arm */}
          <mesh geometry={nodes.Right_Shoulder.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Arm.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Forearm.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Wrist.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Thumb.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Index_Finger.geometry}>
            {boneMaterial}
          </mesh>
          <mesh geometry={nodes.Right_Middle_Finger.geometry}>
            {boneMaterial}
          </mesh>
          <mesh geometry={nodes.Right_Pinky.geometry}>{boneMaterial}</mesh>

          {/* left leg */}
          <mesh geometry={nodes.Left_Upper_Leg.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Leg.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Foot.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Toe_Base.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Left_Toe_End.geometry}>{boneMaterial}</mesh>

          {/* right leg */}
          <mesh geometry={nodes.Right_Upper_Leg.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Leg.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Foot.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Toe_Base.geometry}>{boneMaterial}</mesh>
          <mesh geometry={nodes.Right_Toe_End.geometry}>{boneMaterial}</mesh>

          {/* original skin — hidden */}
          {/* <skinnedMesh name="MAW" geometry={nodes.MAW.geometry} material={materials.MAW_MAT} skeleton={nodes.MAW.skeleton} /> */}
        </group>
        <directionalLight
          position={[0, 0, 0]}
          color="#12ffa0"
          intensity={2}
        />
    </group>
  );
}
